In [69]:
import chainer
import numpy as np
import copy
import pickle

In [4]:
# 配列の形を知りたい時はshape， データ数を知りたい時はsize
a = np.arange(60).reshape(10, 6)
print(a.shape) 
print(a.size)

(10, 6)
60


In [7]:
# 0や1以外での初期化
print(np.empty(10))

[  0.00000000e+000   1.29074254e-231   4.24395921e-314   1.03030787e-061
   2.90316357e-057   1.13283588e-037   5.41265244e-062   2.28636000e-314
   1.49457775e-154   6.99675748e-309]


In [8]:
# 乱数の生成． 通常は一様分布uniformと正規分布normalを知っていれば問題ない．
print(np.random.uniform(0, 1, 3)) # 区間(0,1)の一様分布に従う乱数を3つ生成
print(np.random.normal(1.5, 2.0, 3)) # 平均1.5, 標準偏差2,0の正規分布に従う乱数を3個生成

[ 0.18847768  0.51002299  0.8144795 ]
[-0.17880932  0.25338199  1.35057454]


In [10]:
# 要素をシャッフルした配列を生成． shuffleは配列を破壊的に並び替えるので， 通常はpermutatonを使うのが安全
print(np.random.permutation(range(6))) # permutationは順列の意
print(np.random.permutation(6)) # 省略形

[1 0 5 2 4 3]
[4 5 1 2 3 0]


In [12]:
# 単位行列の生成
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
#  配列の結合
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
print(np.hstack([a,b]), end="\n\n") # horizontal
print(np.vstack([a,b])) # virtical

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
# スライス
a = np.arange(30).reshape(5, 6)
print(a[[0, 2,4], 2])

[ 2 14 26]


In [32]:
# 置換
a = np.arange(30).reshape(5, 6)
a[a%2 == 0] = -1
print(a)

[[-1  1 -1  3 -1  5]
 [-1  7 -1  9 -1 11]
 [-1 13 -1 15 -1 17]
 [-1 19 -1 21 -1 23]
 [-1 25 -1 27 -1 29]]


値渡し；変数の値をコピーする渡し方  
参照渡し：変数を共有するような渡し方  

    
Pythonでは，変数や関数に値を渡す場合すべて参照渡しだが， Immutableな型のみ，値が変更されたときに新たなオブジェクトを生成する(元のオブジェクトは変更されない)．
Mutableな型で値渡しをしたい場合はcopy()を利用．

- 変更不可（Immutable）な型  
    - int, float, str, tuple, bytes, frozenset 等  
- 変更可能（Mutable）な型  
    - list, dict, set, bytearray 等  

In [57]:
#  値渡しと参照渡し
def foo(a):
    print(f"a = {a}, id(a) = {id(a)}") # bと同じ
    a += 1
    print(f"a = {a}, id(a) = {id(a)}") # 新たな領域が確保される

b = 0
foo(b)
print(f"b = {b}, id(b) = {id(b)}") # bの領域が確保される．値は変更されていない

a = 0, id(a) = 4495615968
a = 1, id(a) = 4495616000
b = 0, id(b) = 4495615968


In [43]:
# コピー
a = np.arange(6).reshape(2,3)
print(a, end="\n\n")
b = a
b[0] = 0
print(a, end="\n\n") # 元の配列も変更される

c = a.copy()
c[0] = 1
print(a) # 元の配列は変更されない．

[[0 1 2]
 [3 4 5]]

[[0 0 0]
 [3 4 5]]

[[0 0 0]
 [3 4 5]]


In [70]:
 # 逆行列， 転置行列， 行列式，　固有値
a = np.array([[0, 6, 3], [-2, 7, 2], [0, 0, 3]])
print(a.T, end="\n\n")
print(np.linalg.det(a), end="\n\n") # 行列式
print(np.linalg.inv(a), end="\n\n") # 逆行列
la, v = np.linalg.eig(a)
print(la, end="\n\n") # 固有値
print(v) # 固有ベクトル

[[ 0 -2  0]
 [ 6  7  0]
 [ 3  2  3]]

36.0

[[ 0.58333333 -0.5        -0.25      ]
 [ 0.16666667  0.         -0.16666667]
 [ 0.          0.          0.33333333]]

[ 3.  4.  3.]

[[-0.89442719 -0.83205029  0.69674017]
 [-0.4472136  -0.5547002  -0.01025506]
 [ 0.          0.          0.71725028]]


In [80]:
# 配列の保存と呼び出し
a = np.random.randn(10000).reshape(100, 100)
print(a, end="\n\n")
f = open('a.pickle', 'wb') # a.pickleに書き出される． wだとエラー．
pickle.dump(a, f)
f.close()

f = open("a.pickle", "rb")
a = pickle.load(f)
f.close()
print(a)

[[ 0.15309178 -0.85185388  0.59114131 ...,  0.14839234  0.83567768
  -0.63671937]
 [-0.37338832 -0.33199545  1.93472797 ..., -1.05424288 -0.2511722
   0.33626443]
 [-0.1653209   0.07774827  1.40448837 ..., -1.43479737 -0.78170837
   1.66914773]
 ..., 
 [ 0.08359049  0.99476276 -0.48383243 ..., -0.14521299  0.11700281
  -1.62198993]
 [-1.7400307   0.43200656  0.20137576 ..., -0.73484022  0.75110433
  -1.06945485]
 [-0.66899497 -0.34596118  0.35028989 ..., -0.59147038  0.54949762
   0.92654538]]

[[ 0.15309178 -0.85185388  0.59114131 ...,  0.14839234  0.83567768
  -0.63671937]
 [-0.37338832 -0.33199545  1.93472797 ..., -1.05424288 -0.2511722
   0.33626443]
 [-0.1653209   0.07774827  1.40448837 ..., -1.43479737 -0.78170837
   1.66914773]
 ..., 
 [ 0.08359049  0.99476276 -0.48383243 ..., -0.14521299  0.11700281
  -1.62198993]
 [-1.7400307   0.43200656  0.20137576 ..., -0.73484022  0.75110433
  -1.06945485]
 [-0.66899497 -0.34596118  0.35028989 ..., -0.59147038  0.54949762
   0.92654538]]


In [83]:
a = np.array([1,2,3])
np.save("a.npy", a)
b = np.load("a.npy")
print(b)

[1 2 3]


In [9]:
# 上記で説明したようにChainerは"Define-by-Run"の枠組みを利用しているので、forward計算それ自身がネットワークの定義となります。forward計算を始めるために、入力としてVariableオブジェクトを設定します。ここでは一個の要素を持ったシンプルなn次元配列から始めましょう。
x_data = np.array([5], dtype=np.float32)
x =Variable(x_data) 
y = x**2 -2*x +1
y.data

array([ 16.], dtype=float32)

In [11]:
# backwardは誤差逆伝播法(バックプロパゲーション）を走らせます。
# そしてその勾配が計算され、変数xのgradフィールドに保存されます:
y.backward()

In [12]:
x.grad

array([ 8.], dtype=float32)

In [13]:
z = 2*x
y = x**2 - z + 1
y.backward(retain_grad=True)
z.grad

array([-1.], dtype=float32)